@extends('layouts.app')
@section('content')
@php($other=$conversation->otherUser(auth()->user()))
<div class="mx-auto max-w-3xl"><div class="sticky top-[73px] z-20 -mx-5 mb-4 border-b border-slate-200/80 bg-white/90 px-5 py-4 backdrop-blur-xl lg:rounded-2xl"><div class="flex items-center gap-3"><a href="{{ route('chat.index') }}" class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-100 font-black">←</a><div class="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-100 to-pink-100 font-black text-indigo-700">{{ strtoupper(substr($other->name,0,1)) }}</div><div><h1 class="font-black">{{ $other->name }}</h1><p class="text-xs font-semibold text-emerald-600">● Connected</p></div></div></div>
<div id="messages" class="min-h-[58vh] space-y-3 rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm sm:p-6">@foreach($messages as $message)<div data-message-id="{{ $message->id }}" class="flex {{ $message->sender_id===auth()->id()?'justify-end':'justify-start' }}"><div class="max-w-[82%] rounded-[1.35rem] px-4 py-3 text-sm leading-6 {{ $message->sender_id===auth()->id()?'rounded-br-md bg-slate-950 text-white':'rounded-bl-md bg-slate-100 text-slate-900' }}">{{ $message->body }}</div></div>@endforeach</div>
<form id="message-form" class="sticky bottom-[72px] mt-4 flex gap-2 rounded-3xl border border-slate-200 bg-white/95 p-2 shadow-xl backdrop-blur"><input id="message-input" maxlength="2000" autocomplete="off" class="min-w-0 flex-1 rounded-2xl bg-slate-50 px-4 py-3 text-sm font-medium outline-none focus:bg-white" placeholder="Write a message…"><button id="send-button" class="tap min-w-[72px] rounded-2xl bg-slate-950 px-5 py-3 text-sm font-black text-white">Send</button></form></div>
<script>
const form=document.getElementById('message-form'),input=document.getElementById('message-input'),sendButton=document.getElementById('send-button'),box=document.getElementById('messages'),csrf=document.querySelector('meta[name="csrf-token"]')?.content,myId={{ auth()->id() }},messagesUrl='{{ route('chat.messages',$conversation) }}',storeUrl='{{ route('chat.messages.store',$conversation) }}';
function lastId(){const nodes=box.querySelectorAll('[data-message-id]');let max=0;nodes.forEach(n=>{const id=Number(n.dataset.messageId);if(id>max)max=id});return max}
function addMessage(m){if(document.querySelector('[data-message-id="'+m.id+'"]'))return;const w=document.createElement('div');w.dataset.messageId=m.id;w.className='flex '+(Number(m.sender_id)===Number(myId)?'justify-end':'justify-start');const b=document.createElement('div');b.className='max-w-[82%] rounded-[1.35rem] px-4 py-3 text-sm leading-6 '+(Number(m.sender_id)===Number(myId)?'rounded-br-md bg-slate-950 text-white':'rounded-bl-md bg-slate-100 text-slate-900');b.textContent=m.body;w.appendChild(b);box.appendChild(w);box.scrollTop=box.scrollHeight}
async function pollMessages(){try{const r=await fetch(messagesUrl+'?after='+encodeURIComponent(lastId()),{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)return;const d=await r.json();(d.messages||[]).forEach(addMessage)}catch(e){}}
form.addEventListener('submit',async e=>{e.preventDefault();const body=input.value.trim();if(!body||sendButton.disabled)return;input.value='';sendButton.disabled=true;sendButton.textContent='…';try{const r=await fetch(storeUrl,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({body})});if(!r.ok)throw new Error();const d=await r.json();addMessage(d.message)}catch(e){input.value=body}finally{sendButton.disabled=false;sendButton.textContent='Send';input.focus()}});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});setInterval(pollMessages,2000);box.scrollTop=box.scrollHeight;
</script>
@endsection
