@extends('layouts.app')
@section('content')
<div class="mx-auto max-w-4xl space-y-8">
    <div><p class="font-bold text-indigo-600">LAMII CONNECTIONS</p><h1 class="mt-2 text-4xl font-black">Your people</h1><p class="mt-2 text-slate-600">Waves become connections only when both people agree.</p></div>
    @if(session('success'))<div class="rounded-2xl bg-emerald-50 p-4 font-semibold text-emerald-700">{{ session('success') }}</div>@endif
    <section><h2 class="mb-4 text-xl font-black">Waves waiting for you</h2><div class="space-y-3">@forelse($incoming as $connection)<div class="flex items-center justify-between rounded-2xl border bg-white p-5"><div><p class="font-bold">{{ $connection->sender->name }} waved at you 👋</p><p class="text-sm text-slate-500">{{ $connection->sender->bio }}</p></div><div class="flex gap-2"><form method="POST" action="{{ route('connections.accept', $connection) }}">@csrf<button class="rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white">Wave back</button></form><form method="POST" action="{{ route('connections.decline', $connection) }}">@csrf<button class="rounded-xl border px-4 py-2 font-bold">Ignore</button></form></div></div>@empty<div class="rounded-2xl border bg-white p-6 text-slate-500">No waves waiting for you.</div>@endforelse</div></section>
    <section><h2 class="mb-4 text-xl font-black">Connected</h2><div class="grid gap-3 sm:grid-cols-2">@forelse($accepted as $connection)@php($person = $connection->sender_id === auth()->id() ? $connection->recipient : $connection->sender)<div class="rounded-2xl border bg-white p-5"><p class="font-bold">{{ $person->name }}</p><p class="mt-1 text-sm text-slate-500">{{ $person->bio }}</p><p class="mt-3 text-sm font-semibold text-emerald-600">Connected ✓</p></div>@empty<div class="rounded-2xl border bg-white p-6 text-slate-500 sm:col-span-2">Wave at someone nearby to start making connections.</div>@endforelse</div></section>
    <section><h2 class="mb-4 text-xl font-black">Your outgoing waves</h2><div class="space-y-3">@forelse($outgoing as $connection)<div class="rounded-2xl border bg-white p-5"><p class="font-bold">👋 {{ $connection->recipient->name }}</p><p class="mt-1 text-sm text-slate-500">Waiting for a response.</p></div>@empty<div class="rounded-2xl border bg-white p-6 text-slate-500">You have no pending waves.</div>@endforelse</div></section>
</div>
@endsection
